import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

EMAIL_ADDRESS = os.environ.get("EMAIL_ADDRESS")
EMAIL_APP_PASSWORD = os.environ.get("EMAIL_APP_PASSWORD")

# Defaults to Gmail's SMTP settings; override for other providers via
# SMTP_HOST / SMTP_PORT env vars. See README for a table of common providers.
SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))


def build_html(items):
    today = datetime.now().strftime("%B %d, %Y")
    rows = ""
    for item in items:
        rows += f"""
        <div style="margin-bottom:28px; padding-bottom:24px; border-bottom:1px solid #e5e5e5;">
          <div style="font-size:11px; color:#888; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:4px;">
            {item.get('source','Unknown')} &middot; {item.get('date','')}
          </div>
          <a href="{item.get('link','#')}" style="font-size:17px; font-weight:600; color:#1a1a1a; text-decoration:none; line-height:1.35; display:block; margin-bottom:6px;">
            {item.get('title','No title')}
          </a>
          <div style="font-size:13px; color:#555; margin-bottom:6px;">
            {item.get('authors','')}
          </div>
          <div style="font-size:14px; color:#333; line-height:1.6; margin-bottom:8px;">
            {item.get('summary','')}
          </div>
          <div style="font-size:13px; color:#0066cc; font-style:italic;">
            Why it matters: {item.get('reason','')}
          </div>
        </div>
        """

    if not rows:
        rows = "<p style='color:#888;'>No highly relevant items found today.</p>"

    html = f"""
    <html>
    <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; max-width:640px; margin:0 auto; padding:32px 24px; background:#fff; color:#1a1a1a;">
      <div style="margin-bottom:32px; padding-bottom:20px; border-bottom:2px solid #1a1a1a;">
        <div style="font-size:11px; color:#888; text-transform:uppercase; letter-spacing:0.08em; margin-bottom:6px;">
          Research Digest
        </div>
        <h1 style="font-size:24px; font-weight:700; margin:0 0 4px 0;">{today}</h1>
        <div style="font-size:13px; color:#888;">
          {len(items)} item{'s' if len(items) != 1 else ''} selected
        </div>
      </div>
      {rows}
      <div style="margin-top:32px; font-size:12px; color:#aaa; text-align:center;">
        Generated by your research digest agent
      </div>
    </body>
    </html>
    """
    return html


def build_plaintext(items):
    today = datetime.now().strftime("%B %d, %Y")
    lines = [f"Research Digest — {today}", "=" * 50, ""]
    for item in items:
        lines.append(f"[{item.get('source','')}] {item.get('title','')}")
        lines.append(f"Authors: {item.get('authors','')}")
        lines.append(f"Date: {item.get('date','')}")
        lines.append(f"Link: {item.get('link','')}")
        lines.append(f"{item.get('summary','')}")
        lines.append(f"Why it matters: {item.get('reason','')}")
        lines.append("")
    if not items:
        lines.append("No highly relevant items found today.")
    return "\n".join(lines)


def send_digest(items):
    subject_date = datetime.now().strftime("%b %d")
    subject = f"Research Digest — {subject_date} ({len(items)} items)"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = EMAIL_ADDRESS
    msg["To"] = EMAIL_ADDRESS

    msg.attach(MIMEText(build_plaintext(items), "plain"))
    msg.attach(MIMEText(build_html(items), "html"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(EMAIL_ADDRESS, EMAIL_APP_PASSWORD)
            server.sendmail(EMAIL_ADDRESS, EMAIL_ADDRESS, msg.as_string())
        print(f"Digest sent to {EMAIL_ADDRESS}")
    except Exception as e:
        print(f"Email send error: {e}")
        raise


if __name__ == "__main__":
    sample_items = [
        {
            "source": "arXiv",
            "title": "Sample Paper Title",
            "summary": "A sample summary for testing the email layout.",
            "link": "https://arxiv.org/",
            "authors": "Test Author",
            "date": "2025-01-01",
            "reason": "A sample reason, for testing purposes.",
        }
    ]
    send_digest(sample_items)
